#! /bin/bash
if [ ! ${EUID:-$(id -u)} -eq 0 ]
then
    echo 'You must be root to run this script'
    exit 1
fi

installdir=/usr/share/pywal-discord
themesdir=$HOME/.config/pywal-discord

unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)
        installdir=$HOME/.config/pywal-discord
        themesdir=$HOME/.config/pywal-discord-themes
        ;;
esac

mkdir -p "$themesdir"

if [ -e "$installdir" ]
then
	rm -rf "$installdir"
fi

mkdir "$installdir"
cp ./config/* "$installdir"
if [ "${unameOut}" == "Darwin" ]
then
	cp ./pywal-discord /usr/local/bin
else
	cp ./pywal-discord /usr/bin/
fi
