#!/bin/bash
path="$HOME/.config/BetterDiscord/themes"
theme="default"
config="/usr/share/pywal-discord"
usrconfig="$HOME/.config/pywal-discord"

unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    config="$HOME/.config/pywal-discord"
                path="$HOME/Library/Preferences/BetterDiscord/themes"
                usrconfig="$HOME/.config/pywal-discord-themes"
        ;;
esac

print_usage() {
  echo "Usage: $0 [-t theme] [-p path] [-d]"
  echo "-h                          Display this info"
  echo "-t theme                    Available: [default,abou]"
  echo "-p path/to/folder/or/file   Path where pywal-discord will generate theme. Default: $path"
  echo "-d                          Make path directory where theme will be generated"
}

while getopts 'dp:vt:vh' flag; do
  case "${flag}" in
    d) mkdir -p "$path" ;;
    p) path="${OPTARG}" ;;
    t) theme="${OPTARG}" ;;
    h) print_usage ;;
    *) print_usage 
       exit 1 ;;
  esac
done

# Try to use a user defined theme if it exists
themefile=$usrconfig/pywal-discord-$theme.css
if [ ! -f "$themefile" ]; then
  themefile=$config/pywal-discord-$theme.css
fi

newfile=$path/pywal-discord-$theme.theme.css

# Adapt metadata to theme
sed "s/@name Pywal-Discord/@name Pywal-Discord-$theme/" "$config/meta.css" > /tmp/pywal-discord-meta

cat /tmp/pywal-discord-meta "$HOME/.cache/wal/colors.css" "$themefile" > "$newfile" 
if [ ! -f "$newfile" ]
then
    echo ⚠️ THEME WAS NOT CREATED ⚠️ 
    echo Try to change path with -p because $path doesn\'t exist, or add -d to create it
    exit 1
fi
