#!/bin/bash
path='$HOME/.config/BetterDiscord/themes'
theme="default"
print_usage() {
  echo "Usage: $0 [-t theme] [-p path]"
  echo "-t theme                    Available: [$theme,abou]"
  echo "-p path/to/folder/or/file   Default $path, (use when using different loader than BD"
}

while getopts 'p:vt:vh' flag; do
  case "${flag}" in
    p) path="${OPTARG}" ;;
    t) theme="${OPTARG}" ;;
    h) print_usage ;;
    *) print_usage 
       exit 1 ;;
  esac
done
config="$HOME/.config/pywal-discord"
cat $config/meta.css $HOME/.cache/wal/colors.css $config/pywal-discord-$theme.css > $config/pywal-discord-$theme.theme.css
cp $config/pywal-discord-$theme.theme.css $path 
